name: CI
on:
  - push
  - pull_request

jobs:
  ci:
    name: "Build & Test (React v${{ matrix.react_version}})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react_version:
          - "0.14.9"
          - "15.0"
          - "15"
          - "16.0"
          - "16"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "lts/*"
        cache: 'yarn'
    - run: yarn install
    - run: yarn add react@${{ matrix.react_version }}
    - run: yarn list --pattern 'react'
    - run: yarn run pretest
    - run: yarn run tests-only
    - run: yarn run build
